#include "ui_sim.h"

ui_sim_data_t sim_ui_data = {0};

const ui_sim_presenter_t sim_data = {
    .radio_on = aic_srv_tele_radio_on,
    .radio_register = aic_srv_tele_radio_register,
    .call_register = aic_srv_tele_call_register,
    .get_version = aic_get_version,
    .get_imei = aic_srv_tele_radio_get_imei,
    .radio_have_cali = aic_srv_tele_radio_have_cali,
    .sim_get_status = aic_srv_tele_sim_get_status,
    .sim_get_imsi = aic_srv_tele_sim_get_imsi,
    .sim_get_msisdn  = aic_srv_tele_sim_get_msisdn,
    .get_signal_info = aic_srv_tele_radio_get_signal_info,
    .get_cell_info = aic_srv_tele_radio_get_cell_info,
    .get_neighbor_cell_info_list = aic_srv_tele_radio_get_neighbor_cell_info_list,
    .get_reg_status = aic_srv_tele_radio_get_reg_status,
    .get_operator_info = aic_srv_tele_radio_get_operator_info,
    .have_ims_reg = aic_srv_tele_radio_have_ims_reg,
    .get_internet_pdp_info = aic_srv_tele_data_get_internet_pdp_info,
    .radio_start_search = aic_srv_tele_radio_start_search,
    .get_network_dl_speed = aic_network_speed_download_test,
    .get_network_ul_speed = aic_network_speed_upload_test,
    .set_auto_answer = aic_srv_tele_call_set_auto_answer,
    .get_auto_answer = aic_srv_tele_call_is_auto_answer,
    .call_have_volte_reg = aic_srv_tele_call_have_volte_reg,
    .set_voice_enable_loopback = aic_srv_voice_enable_loopback,
    .get_voice_enable_loopback = aic_srv_voice_is_enable_loopback,
    .set_enable_volte = aic_srv_tele_call_volte_enable,
    .get_enable_volte = aic_srv_tele_call_is_volte_enable,
    .tele_call_dail = aic_srv_tele_call_dial,
    .tele_sms_register = aic_srv_tele_sms_register,
    .tele_sms_send = aic_srv_tele_sms_send,
    .tele_sms_load_list = aic_srv_tele_sms_load_in_sim,
    .tele_sms_get_smsc = aic_srv_tele_sms_get_smsc,
    .ctrl_power_on = aic_ctrl_power_on,
    .ctrl_reset = aic_ctrl_reset,
    .ctrl_assert = aic_ctrl_assert,
    .set_log_level = alog_set_level,
    .get_log_level = alog_get_level,
};
