/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __BT_WATCH_STY_H__
#define __BT_WATCH_STY_H__

#define  SCENE_CUBE_ROTATE    0x9630ea06
#define  PIC_CUBE    0x79c22d30

#endif /* #ifndef __BT_WATCH_STY_H__ */
