obj-$(CONFIG_SPP_TEST_SUPPORT) = spp_test_background.o
obj-$(CONFIG_SPP_TEST_SUPPORT) = show_fw_version.o
obj-$(CONFIG_SPP_TEST_SUPPORT) = abtp_entry.o
obj-$(CONFIG_SPP_TEST_SUPPORT) = spp_mic_upload.o
obj-$(CONFIG_SPP_TEST_SUPPORT) = spp_audio_play.o
obj-$(CONFIG_SPP_TEST_SUPPORT) = mic_test_entry.o
