
all:
	gcc -Wall -O2 -o cfg_source.exe 	cfg_source.c
	gcc -Wall -O2 -o cfg_maker.exe  	cfg_maker.c
	gcc -Wall -O2 -o xml_source.exe 	xml_source.c
	gcc -Wall -O2 -o xml_maker.exe  	xml_maker.c
	gcc -Wall -O2 -o MakeExtCfg.exe 	MakeExtCfg.c
	gcc -Wall -O2 -o xml_cleaner.exe 	xml_cleaner.c
	gcc -Wall -O2 -o copy_cfg_info.exe 	copy_cfg_info.c

	strip cfg_source.exe
	strip cfg_maker.exe
	strip xml_source.exe
	strip xml_maker.exe
	strip MakeExtCfg.exe
	strip xml_cleaner.exe
	strip copy_cfg_info.exe
