obj-y += nv_analyze/nv_protocol.o
obj-y += nv_sppble/nv_ble_stream.o
obj-y += nv_sppble/nv_ble_stream_ctrl.o
obj-y += nv_analyze/library/aes.o
obj-y += nv_analyze/library/cipher.o
obj-y += nv_analyze/library/cipher_wrap.o
obj-y += nv_analyze/library/gcm.o
obj-y += nv_analyze/library/platform_util.o