obj-$(CONFIG_OTA_UPGRADE) += ota_upgrade.o ota_image.o ota_manifest.o \
			     ota_storage.o ota_breakpoint.o
obj-$(CONFIG_OTA_BACKEND_BLUETOOTH) += ota_backend_bt.o
obj-$(CONFIG_OTA_BACKEND_SDCARD) += ota_backend_sdcard.o
obj-$(CONFIG_OTA_BACKEND_TEMP_PART) += ota_backend_temp_part.o
obj-$(CONFIG_OTA_FILE_PATCH) += ota_file_patch.o hpatch.o
obj-$(CONFIG_OTA_PRODUCT_SUPPORT) += ota_upgrade_host.o
obj-$(CONFIG_OTA_BLE_MASTER_SUPPORT) += ota_upgrade_host.o
obj-y += libota_version.o